# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    user_columns = {column.name for column in database.get_columns("users")}
    if "hints" not in user_columns:
        migrator.add_columns("users", hints=peewee.BooleanField(default=True))

    server_columns = {column.name for column in database.get_columns("servers")}
    if "show_status" not in server_columns:
        migrator.add_columns("servers", show_status=peewee.BooleanField(default=True))


def rollback(migrator, database, **kwargs):
    server_columns = {column.name for column in database.get_columns("servers")}
    if "show_status" in server_columns:
        migrator.drop_columns("servers", ["show_status"])

    user_columns = {column.name for column in database.get_columns("users")}
    if "hints" in user_columns:
        migrator.drop_columns("users", ["hints"])
