# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns(
        "servers",
        auto_restart=peewee.BooleanField(default=False),
        auto_restart_time=peewee.CharField(default="04:00"),
        auto_restart_timezone=peewee.CharField(default="UTC"),
    )
    """
    Write your migrations here.
    """


def rollback(migrator, database, **kwargs):
    migrator.drop_columns(
        "servers",
        ["auto_restart", "auto_restart_time", "auto_restart_timezone"],
    )
    """
    Write your rollback migrations here.
    """
