# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns("schedules", timezone=peewee.CharField(default=""))


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("schedules", ["timezone"])
