# yamllint disable rule:line-length
---
name: Build Docker Images

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - dev
      - "ianga/**"
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    env:
      SHOULD_PUSH: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' }}
    outputs:
      date: ${{ steps.date.outputs.date }}
      tag: ${{ steps.branch.outputs.tag }}
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v4
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GitHub Container Registry
        if: env.SHOULD_PUSH == 'true'
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      #      - name: Login to Docker Hub
      #        if: github.event_name != 'pull_request'
      #        uses: docker/login-action@v1
      #        with:
      #          username: ${{ secrets.DOCKER_USERNAME }}
      #          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date
        id: date
        run: echo "date=$(date +"%Y-%m-%dT%H:%M:%SZ")" >> "$GITHUB_OUTPUT"

      - name: Get Crafty version
        id: version
        run: |
          MAJOR=$(cat app/config/version.json | jq '.major' )
          MINOR=$(cat app/config/version.json | jq '.minor' )
          SUB=$(cat app/config/version.json | jq '.sub' )
          echo "version=$MAJOR.$MINOR.$SUB" >> "$GITHUB_OUTPUT"

      - name: Get branch tag
        id: branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "tag=latest" >> "$GITHUB_OUTPUT"
          else
            TAG=$(echo "${{ github.ref_name }}" | tr '/_' '--' | sed -E 's/[^A-Za-z0-9.-]+/-/g')
            echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          push: ${{ env.SHOULD_PUSH == 'true' }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ steps.branch.outputs.tag }}
          cache-to: type=inline
          build-args: |
            BUILD_DATE=${{ steps.date.outputs.date }}
            BUILD_REF=${{ github.sha }}
            CRAFTY_VER=${{ steps.version.outputs.version }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.branch.outputs.tag }}

#           {{ GITHUB_REPOSITORY }}:${{ steps.branch.outputs.tag }}
